const airtableSchools = {
        "0":"San Jose State University",
        "4":"University of California Riverside ",
        "6":"Mission College",
        "8":"Colorado State University",
        "9":"University of South Florida",
        "10":"University of California Davis",
        "12":"univeristy of califronia santa cruz",
        "16":"University of Michigan ",
        "17":"Stanford University",
        "19":"University of Houston - Main Campus",
        "20":"Northwestern University",
        "21":"University of Toronto",
        "22":"Grand Valley State University ",
        "23":"Rutgers University Newark",
        "24":"Normandale community college ",
        "25":"Northeastern University",
        "26":"New Jersey Institute of Technology",
        "27":"University of Illinois at Chicago ",
        "28":"University of Washington",
        "29":"University of Maryland, College Park",
        "30":"University of California, Riverside",
        "31":"Loyola University Chicago",
        "32":"Denison University ",
        "33":"Georgia institute of technology",
        "34":"University of Texas at Dallas",
        "35":"Northern Virginia Community College",
        "36":"University of Miami",
        "37":"University of Windsor",
        "38":"Rutgers University - New Brunswick",
        "39":"University of Texas Southwestern Medical Center",
        "40":"Haas school of business ",
        "42":"The George Washington University",
        "43":"Baruch college",
        "44":"University of California Berkeley",
        "45":"Hunter College",
        "47":"York University (Toronto, Canada)",
        "48":"DePaul University ",
        "49":"University of Florida",
        "50":"National University of Singapore",
        "52":"Brooklyn College",
        "53":"University College London",
        "54":"University at Albany, SUNY",
        "55":"Santa Clara University ",
        "57":"University of Cincinnati ",
        "58":"Teaneck High School",
        "59":"Rutgers University",
        "60":"University of Western Ontario",
        "61":"Arizona State University ",
        "62":"University of Maryland",
        "63":"University of Texas at Austin",
        "64":"Georgia Institute of Technology",
        "65":"Auburn University ",
        "66":"university of missouri-kansas city ",
        "67":"University of California Los Angeles",
        "68":"The University of Texas at Dallas",
        "71":"University of the Incarnate Word ",
        "72":"George Mason University ",
        "73":"University of Houston ",
        "74":"University of California Berkeley",
        "75":"University of Pennsylvania ",
        "76":"University of Manchester",
        "77":"University of Illinois at Chicago",
        "78":"University of Houston",
        "80":"Rowan University ",
        "81":"Drexel University",
        "82":"The London school of economics and political science",
        "83":"Aston University",
        "84":"Ryerson University",
        "85":"Binghamton University ",
        "86":"North Carolina State University",
        "87":"Northern Alberta Institute of Technology (NAIT)",
        "88":"The Univeristy of Texas at Dallas",
        "91":"University of Wyoming",
        "92":"Cal state San Bernardino ",
        "93":"Adelphi University ",
        "94":"University of California, Irvine",
        "96":"The University of Texas at Dallas ",
        "97":"University of Toronto ",
        "99":"University of Minnesota - Twin Cities",
        "100":"university of illinois at chicago",
        "101":"City of New York- Hunter College",
        "102":"Florida International University",
        "106":"Northwestern University ",
        "109":"Duke",
        "111":"University of Texas at Austin ",
        "112":"University of Michigan",
        "113":"University of Michigan Ann Arbor",
        "118":"Santa Clara University",
        "119":"California state polytechnic university, Pomona",
        "120":"Purdue University",
        "124":"University of California Berkeley",
        "126":"West Valley Community College",
        "129":"Heriot-Watt University (Edinburgh)",
        "133":"University of Washington Bothell",
        "134":"Central Michigan University ",
        "136":"University of California, Davis",
        "137":"Broward College"
};

const uniqueSchools = (schools)=>{
    let schoolsArray = Object.keys(schools).map((key)=>{
        return schools[key].replace(/\s+/g, "").replace(/([.,-])/g, "").toUpperCase();
    });
    let uniqueSet = [...new Set(schoolsArray)];
    console.log("spaces and char removed length", schoolsArray.length);
    console.log("Unique set", uniqueSet, "Length", uniqueSet.length);
}
uniqueSchools(airtableSchools);